# Generated by Django 4.2 on 2026-01-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
        migrations.AddField(
            model_name='ad',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='description_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='location_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='location_ta',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='title_ta',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LOV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('lic', models.CharField(help_text='Language-independent code', max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('high_low', models.BooleanField(default=True, help_text='True for high, False for low')),
                ('is_active', models.BooleanField(default=True)),
                ('parent_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.lov')),
            ],
            options={
                'unique_together': {('type', 'lic', 'language')},
            },
        ),
    ]
