# Generated by Django 4.2 on 2026-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_ad_description_remove_ad_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='description_ta',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='location_ta',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title_ta',
        ),
        migrations.AddField(
            model_name='ad',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ad',
            name='title',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ad',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
