# Generated by Django 4.2 on 2026-01-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ad_description_en_remove_ad_description_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.JSONField(default=dict, help_text="Multilingual name, e.g. {'en': 'Chennai', 'ta': 'சென்னை'}"),
        ),
    ]
