# Generated by Django 4.2 on 2026-01-16 08:21

from django.db import migrations, models


def migrate_city_data(apps, schema_editor):
    Ad = apps.get_model('ads', 'Ad')
    City = apps.get_model('ads', 'City')
    for ad in Ad.objects.all():
        city_obj = ad.city
        ad.city = city_obj.name.get('en', 'CHENNAI').upper().replace(' ', '')  # e.g. 'Chennai' -> 'CHENNAI'
        ad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_city_name_to_json'),
    ]

    operations = [
        migrations.RunPython(migrate_city_data),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(choices=[('CHENNAI', 'Chennai'), ('MUMBAI', 'Mumbai'), ('DELHI', 'Delhi'), ('BANGALORE', 'Bangalore'), ('HYDERABAD', 'Hyderabad')], max_length=20),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
