# Generated by Django 4.2 on 2026-01-16 10:21

from django.db import migrations, models


def convert_ad_fields(apps, schema_editor):
    Ad = apps.get_model('ads', 'Ad')
    for ad in Ad.objects.all():
        ad.title = ad.title.get('en', ad.title.get('ta', 'No Title'))
        ad.description = ad.description.get('en', ad.description.get('ta', 'No Description'))
        ad.location = ad.location.get('en', ad.location.get('ta', 'No Location'))
        ad.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_change_ad_city_to_charfield'),
    ]

    operations = [
        migrations.RunPython(convert_ad_fields),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
