# Generated by Django 4.2 on 2026-01-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_change_ad_fields_to_single_strings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lov',
            name='high_low',
        ),
    ]
