# Generated by Django 4.2 on 2026-01-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_remove_high_low_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lov',
            unique_together={('type', 'lic', 'display_name', 'language', 'is_active')},
        ),
    ]
