# Generated by Django 4.2 on 2026-01-21 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_add_status_and_blocked_user'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE ads_blockeduser SET status = (SELECT id FROM ads_lov WHERE type='BLOCKED_USER_STATUS' AND lic = ads_blockeduser.status)",
            reverse_sql="UPDATE ads_blockeduser SET status = (SELECT lic FROM ads_lov WHERE id = ads_blockeduser.status_id)"
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'BLOCKED_USER_STATUS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ads.lov'),
        ),
    ]
