# Generated by Django 4.2 on 2026-01-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_blockeduser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='status',
            field=models.CharField(default='BLOCKED', max_length=20),
        ),
        migrations.RunSQL(
            "UPDATE ads_blockeduser SET status = (SELECT lic FROM ads_lov WHERE id = CAST(status AS INTEGER))",
            reverse_sql="UPDATE ads_blockeduser SET status_id = (SELECT id FROM ads_lov WHERE type='BLOCKED_USER_STATUS' AND lic = status)"
        ),
    ]
