# Generated by Django 4.2 on 2026-01-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_blockeduser_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lov',
            options={'ordering': ['order', 'display_name']},
        ),
        migrations.AddField(
            model_name='lov',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
    ]
